#!/usr/bin/env python

import os
import stat
import sys
import glob
import subprocess
import shutil
from pprint import pprint


class PGbouncer:
    def __init__(self, argv):
        self.args = argv[1:]
        self.ip            = None                           # host ip on public interface
        self.network       = None                           # host network 
        self.cidr          = None                           # host CIDR 
        self.conf          = "/etc/pgbouncer/pgbouncer.ini" # pgbouncer config file
        self.authFile      = "/etc/pgbouncer/userlist.txt"  # pgbouncer auth file
        self.unixSocketDir = "/var/run/postgresql"          # unix socket dir for postgres 
        self.users         = ["sdlapp",                     # pgbouncer users
                              "mapuser", 
                              "wsuser", 
                              "jobuser"] 

        self.findSysValues()

    def findSysValues(self):
        self.getNetworkInfo()

    def getNetworkInfo(self):
        """ find host network info for public interface """
        cmd = "rocks list host attr localhost | grep Kickstart_Public"
        info, err = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        lines = info.split("\n")
        for line in lines:
            if len(line):
                parts = line.split()
                if parts[1]  == "Kickstart_PublicAddress": self.ip = parts[2]
                if parts[1]  == "Kickstart_PublicNetwork": self.network = parts[2]
                if parts[1]  == "Kickstart_PublicNetmaskCIDR": self.cidr = parts[2]

        if self.ip == None or self.network == None or self.cidr == None:
            print "Missing information about public interface "
            sys.exit(1)

    def getPerms(self, config):
        """ find permissions and ownership for the config file """
        stats = os.stat(config)
        self.uid = stats[stat.ST_UID]
        self.gid = stats[stat.ST_GID]

    def readFile(self, fname):
        """ read file, return content"""
        fin = open(fname, "r")
        lines = fin.readlines()
        fin.close()
        return lines

    def writeFile(self, fname, content):
        """ write file """
        fout = open(fname, "w")
        fout.write(content)
        fout.close()

    def makeConfigFile(self):
        """ create new pgbouncer.ini file """

        # make a copy of orig file, use original ownership and permissions
        fname = self.conf 
        fcopy = fname + ".orig"
        fcopy = "/tmp/" + os.path.basename(fname) + ".orig"  #FIXME rm
        self.getPerms(fname)
        shutil.copy2(fname, fcopy)
        os.chown(fcopy, self.uid, self.gid)

        # read defaults from original file
        content = self.readFile(fname)
        defaultLines = self.defaultConfig(content)

        # create new config file, set original ownership and permissions
        newLines = self.makePGBlines()
        fnew = fname
        fnew = "/tmp/" + os.path.basename(fname)  #FIXME rm

        self.writeFile(fnew, defaultLines + newLines)
        shutil.copymode(fname, fnew)
        os.chown(fnew, self.uid, self.gid)

        
    def defaultConfig(self, lines):
        """ read original pgbouncer.ini content, skip lines to be overwritten, return non-comment lines """

        comments = [";", " ", "\t", "\n"]
        keywords = ["logfile", "pidfile", "auth_file", "listen_port", "pool_mode" ]
        content = ""
        for line in lines:
            if line[0] in comments:
                continue
            if line.split()[0] in keywords: 
                content += line

        return content

    def makePGBlines(self):
        """ create lines to add to pgbouncer.ini configuration file """
        addLines = ";; Specific to Lifemapper\n"
        addLines += "[databases]\n"
        addLines += "* = host=%s\n\n" % self.ip
        addLines += ";; Configuration section\n"
        addLines += "[pgbouncer]\n\n"
        addLines += "listen_addr = %s/%s\n" % (self.network, self.cidr)
        addLines += "unix_socket_dir  = %s\n" % self.unixSocketDir
        addLines += "auth_type = md5\n"
        addLines += "auth_file = /etc/pgbouncer/userlist.txt\n"
        addLines += "admin_users =\n"
        addLines += "stats_users =\n"

        return addLines        

    def makeAuthLines(self):
        """ create lines for userlist.txt file """
        import hashlib
        key_string = "SecretPassword"
        salt = "1Ha7"
        hash = hashlib.md5( salt + key_string ).hexdigest()

    def makeAuthFile(self):
        """ create pgbouncer auth file """

        # find owner permissiosn on unix socket dir
        self.getPerms(self.unixSocketDir)

        # create auth file content
        lines = self.makeAuthLines()

        # write auth file
        fnew = self.auth
        fnew = "/tmp/" + os.path.basename(fname)  #FIXME rm
        self.writeFile(fnew, lines)
        shutil.copymode(fname, fnew)
        os.chown(fnew, self.uid, self.gid)

    def runTest(self):
        """ test output """
        pprint (self.__dict__)

    def run(self):
        self.makeConfigFile()
        self.makeAuthFile()
        self.runTest() #FIXME rm

if __name__ == "__main__":
        app=PGbouncer(sys.argv)
        app.run()

